// 综合查询
export const SET_SQL_PARAMS = 'SET_SQL_PARAMS'
export const SET_NAVIGATION = 'SET_NAVIGATION'
export const SET_STATISTICAL = 'SET_STATISTICAL'
export const IMAGE_INDEX = 'IMAGE_INDEX'
export const VIDEO_PANEL = 'VIDEO_PANEL'
export const ROAD_WATCH = 'ROAD_WATCH'
export const INPUT_VALUE = 'INPUT_VALUE'
// 阻断详情
export const SET_GSGX_SQL_PARAMS = 'SET_GSGX_SQL_PARAMS'
// 构造物面板
export const GOU_ZAO_WU = 'GOU_ZAO_WU'
// 刷新树
export const REFRESH_TREE = 'REFRESH_TREE'
export const SET_USER_INFO = 'SET_USER_INFO'
export const USER_MENU_SHOW = 'USER_MENU_SHOW'

// 显示某个面板
export const SET_PANEL = 'SET_PANEL'
// 显示某个弹窗
export const SET_SHOW_POPUP = 'SET_SHOW_POPUP'
// 显示monit列表
export const SHOW_MONIT_LIST = 'SHOW_MONIT_LIST'

// 事件中使用
export const SET_CAMERA_LIST = 'SET_CAMERA_LIST'
// 地图
const SET_MAP_LOAD_STATE = 'SET_MAP_LOAD_STATE'
const SET_TOOL_PANEL = 'SET_TOOL_PANEL'
const MAP_RIGHT_CLICK = 'MAP_RIGHT_CLICK'
const MAP_ADD_CLICK = 'MAP_ADD_CLICK'

// 标绘
const SET_PLOT_BACKGROUND_COLOR = 'SET_PLOT_BACKGROUND_COLOR'
const SET_PLOT_BORDERCOLOR = 'SET_PLOT_BORDERCOLOR'
const SET_PLOT_BORDERWIDTH = 'SET_PLOT_BORDERWIDTH'
const SET_PLOT_OPACITY = 'SET_PLOT_OPACITY'
// 周边搜索
const LAYERS_PERMISTER_STATE = 'LAYERS_PERMISTER_STATE'

// 路径分析
const SET_PATHANALYSIS_ORIGINS = 'SET_PATHANALYSIS_ORIGINS'
const SET_PATHANALYSIS_DESTINATION = 'SET_PATHANALYSIS_DESTINATION'
const SET_PATHANALYSIS_PASS = 'SET_PATHANALYSIS_PASS'
const SET_PATHANALYSIS_AVOID = 'SET_PATHANALYSIS_AVOID'

// 管制
const SHOW_LEGEND = 'SHOW_LEGEND'

// 基础设施监测
const SET_TUNNEL_ACTIVE = 'SET_TUNNEL_ACTIVE'
const SET_BRIDGE_ACTIVE = 'SET_BRIDGE_ACTIVE'

// 气象播放组件
const SET_WEATHER_LAYERNAME = 'SET_WEATHER_LAYERNAME'
const SET_WEATHER_SHOW = 'SET_WEATHER_SHOW'
const SET_WEATHER_LEGEND = 'SET_WEATHER_LEGEND'

// 地图查询
const SET_PERIMETER_LOCATION = 'SET_PERIMETER_LOCATION'
const SET_PERIMETER_LAYER = 'SET_PERIMETER_LAYER'
const SET_PULLBOX_LAYER = 'SET_PULLBOX_LAYER'
const SET_PULLBOX_PARAMS = 'SET_PULLBOX_PARAMS'

// 工具
const LAYERS_STATE = 'LAYERS_STATE'
const PLOT_STATE = 'PLOT_STATE'
const IS_FULL_SCREEN = 'IS_FULL_SCREEN'
// 快速定位
const SET_COORDINATES_ORI_SHOW = 'SET_COORDINATES_ORI_SHOW'
const SET_MARK_ORI_SHOW = 'SET_MARK_ORI_SHOW'
const SET_MAPORI_TYPE = 'SET_MAPORI_TYPE'
const SET_PULLBOX_UUID = 'SET_PULLBOX_UUID'

// 气象
const LAYER_CONTROL = 'LAYER_CONTROL'
const WEATHER_TYPE = 'WEATHER_TYPE'
const WEATHER_CLEAR = 'WEATHER_CLEAR'
const IS_SHOW_VIDEO = 'IS_SHOW_VIDEO'
const SHOW_DETAIL_INFO = 'SHOW_DETAIL_INFO'
const IS_SHOW_BRIEF_DETAIL = 'IS_SHOW_BRIEF_DETAIL'
const REFRESH_TIMER = 'REFRESH_TIMER'

const ROAD_TYPE = 'ROAD_TYPE'
export {
  REFRESH_TIMER,
  LAYER_CONTROL,
  SET_MAP_LOAD_STATE,
  SET_TOOL_PANEL,
  MAP_RIGHT_CLICK,
  SET_PLOT_BACKGROUND_COLOR, // 标绘要素背景色
  SET_PLOT_BORDERCOLOR, // 标绘要素边框色
  SET_PLOT_BORDERWIDTH, // 标绘要素边框宽度
  SET_PLOT_OPACITY, // 标绘要素背景透明度
  SET_PATHANALYSIS_ORIGINS, // 路径分析起点
  SET_PATHANALYSIS_DESTINATION, // 路径分析终点
  SET_PATHANALYSIS_PASS, // 路径分析途径点
  SET_PATHANALYSIS_AVOID, // 路径分析规避点
  SET_BRIDGE_ACTIVE,
  SET_TUNNEL_ACTIVE,
  SET_WEATHER_LAYERNAME,
  SET_WEATHER_SHOW,
  SET_WEATHER_LEGEND,
  SET_PERIMETER_LOCATION,
  SET_PERIMETER_LAYER,
  SET_PULLBOX_PARAMS,
  SET_COORDINATES_ORI_SHOW,
  SET_MARK_ORI_SHOW,
  SET_MAPORI_TYPE,
  SET_PULLBOX_UUID,
  SET_PULLBOX_LAYER,
  LAYERS_STATE,
  PLOT_STATE,
  IS_FULL_SCREEN,
  LAYERS_PERMISTER_STATE,
  SHOW_LEGEND,
  WEATHER_TYPE,
  WEATHER_CLEAR,
  MAP_ADD_CLICK,
  IS_SHOW_VIDEO,
  ROAD_TYPE,
  SHOW_DETAIL_INFO,
  IS_SHOW_BRIEF_DETAIL
}
